architect:
  - egor78945
assets:
  settings.xml: egor78945/secrets#assets/settings.xml
  secring.gpg: egor78945/secrets#assets/secring.gpg
  pubring.gpg: egor78945/secrets#assets/pubring.gpg
docker:
  image: l3r8y/rultor-image:1.0.3
release:
  pre: false
  sensetive:
    - settings.xml
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    echo "before GRADLEEEEEEEEEEEEEE"
    ./gradlew version -PnewVersion="${tag}"
    echo "after GRAGLEEEEEEEEEEEE"
    git commit -am "${tag}"
    ./gradlew clean publish -x test --info